### ISSUE TITLE
Make the project meet community standards

### ISSUE THREAD

**Issue by Arsenic-ATG** [Arsenic-ATG/Tetris#37]
This is a meta issue tracking dev of all the changes required to lay down to get this project meet open source community standards.

- [x] README.md
- [x] Contributing.md ( individual issue #35 )
- [x] Code of conduct ( individual issue #36 )
- [x] [License](https://github.com/Arsenic-ATG/Tetris/blob/master/LICENSE)
- [x] Issue templates ( individual issue #38 )
- [x] pull request template (individual issue #39 )

**Comment by Arsenic-ATG** [comment]
decreasing the priority of the issue as the pull request template is only task left which is optional

**Comment by Arsenic-ATG** [comment]
closing this as completed
